<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="RabbitMQ.Client" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Email/" />
    <Folder Include="Messaging/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
